defaults:
  - override /database@_global_: island_small
  - override /evolution@_global_: small_budget
  - override /task@_global_: "{task_name}"
  - override /cluster@_global_: local
  - _self_


# Override specific parameters

job_config:
  python_path: "{job_config.python_path}"

variant_suffix: "{variant_suffix}"

evo_config:
  llm_models: ["local-gptoss-unsloth-http://127.0.0.1:8080/v1"]
  meta_llm_models: ["local-gptoss-unsloth-http://127.0.0.1:8080/v1"]
  embedding_model: "local-nomic-embed-text:v1.5-http://localhost:11434/v1"
  num_generations: 50