evaluate_function:
  _target_: examples.alpha_evolve_math_problems.first_autocorr_ineq.evaluate.main
  program_path: ???
  results_dir: ???


exp_name: "shinka_first_autocorr_ineq"

evo_config:
  language: python
  job_type: "local"
  python_path: "examples/first_autocorr_ineq/.venv/bin/python"